Models/Cart.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FifthTemplateforfoodordering.Models
{
    public class Cart
    {
        [Key]
        public int CartId { get; set; }
        
        public int UserId { get; set; }

        
        public int FoodId { get; set; }
        public int Qnt { get; set; }
        public virtual User User { get; set; }
        public virtual Food Food { get; set; }

    }
}

Models/OrderDetails.cs
using System.ComponentModel.DataAnnotations;

namespace FifthTemplateforfoodordering.Models
{
    public class OrderDetails
    {
        [Key]
        public int Id { get; set; }
        public int OrderId { get; set; }
       public int FoodId { get; set; }
        public int Qnt { get; set; }
        public float Price { get; set; }
        public float TotalPrice { get; set; }
        public virtual OrderMaster OrderMaster { get; set; }
        public virtual Food Food { get; set; }
        //public OrderDetails()  
        //{

        //}
        //public OrderDetails(Food Food, int qnt)
        //{
        //    this.Food = Food;
        //    this.Qnt = qnt;
        //}
    }
}

Controllers/CartController.cs
using FifthTemplateforfoodordering.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace FifthTemplateforfoodordering.Controllers
{
    public class CartController : Controller
    {
        private readonly FoodContext fd;
        private readonly ISession session;

        public CartController(FoodContext fd, IHttpContextAccessor httpContextAccessor)
        {
            this.fd = fd;
            session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Index()
        {
            return View();
        }
        //public IActionResult MyCart(int? FoodId)
        //{
        //    var result = (from i in fd.Foods
        //                  where i.FoodId == FoodId
        //                  select i.FoodId).SingleOrDefault();
        //    HttpContext.Session.SetString("FoodId", "result");
            
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult MyCart(Cart C)
        //{
        //    fd.Cart.Add(C);
        //    fd.SaveChanges();
        //    return RedirectToAction("Cart");
        //}
        //public IActionResult Cart()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult Cart([Bind("UserId,FoodId,Qnt")] Cart C)
        //{
        //    OrderMaster orderMaster = new OrderMaster();
        //    orderMaster.UserId = C.UserId;
        //    OrderDetails orderDetails = new OrderDetails();
        //    orderDetails.FoodId = C.FoodId;
        //    orderDetails.Qnt = C.Qnt;
        //    fd.SaveChanges();
        //    fd.Cart.RemoveRange(fd.Cart.ToList());
        //    fd.SaveChanges();
        //    return RedirectToAction("Index");
        //}
        public IActionResult AddtoCart(int? FoodId)
        {
            var P = (from i in fd.Foods
                     where i.FoodId == FoodId
                     select i).SingleOrDefault(); 
            string UserId = HttpContext.Session.GetString("UserId");
            return View(P);
        }
        [HttpPost]
        public IActionResult AddtoCart(int Qnt,int? FoodId)
        {
            string UserId= HttpContext.Session.GetString("UserId");
            int b = int.Parse(UserId);
            Cart C = new Cart();
            var F= fd.Foods.FirstOrDefault(i => i.FoodId == FoodId);
            C.UserId = b;
            C.FoodId = F.FoodId;
            C.Qnt = Qnt;
            fd.Add(C);
            fd.SaveChanges();
            return RedirectToAction("ViewCart");
        }
        [HttpGet]
        public IActionResult ViewCart()
        {
            string UserId=HttpContext.Session.GetString("UserId");
            int b=int.Parse(UserId);
            List<Cart> result=(from i in fd.Cart.Include(x=>x.Food)
                               where i.UserId == b
                               select i).ToList();
            return View(result);
        }
        [HttpPost]
        [ActionName("ViewCart")]
        public IActionResult ViewCartDetails()
        {
            string UserId = HttpContext.Session.GetString("UserId");
            int b = int.Parse(UserId);
            var c = (from i in fd.Cart
                     where i.UserId == b
                     select i.FoodId).SingleOrDefault();
            var F= fd.Foods.FirstOrDefault(i => i.FoodId == c);
            List<Cart> list = (from i in fd.Cart
                               where i.UserId == b
                               select i).ToList();
            OrderMaster orderMaster = new OrderMaster();
            orderMaster.UserId = int.Parse(UserId);
            fd.Add(orderMaster);
            fd.SaveChanges();
            List<OrderDetails> orderDetails = new List<OrderDetails>();
            foreach (var item in list)
            {
                OrderDetails od = new OrderDetails();
                od.OrderId = orderMaster.OrderId;
                od.FoodId = item.FoodId;
                od.Qnt = item.Qnt;
                od.Price = F.price;
                od.TotalPrice = od.Qnt * od.Price;
                //orderDetails.Add(od); //S
                fd.OrderDetails.Add(od);
                fd.SaveChanges();
                
            }
            //fd.Add(orderDetails);
            orderDetails.AddRange(fd.OrderDetails);
            orderMaster.TotalPrice = orderDetails.Sum(i=>i.TotalPrice);
            fd.SaveChanges();
            
            return RedirectToAction("Emptylist");
         }
        public IActionResult Delete(int? CartId)
        {
            if (CartId == null)
            {
                return NotFound();
            }

            var val = fd.Cart
                .FirstOrDefault(m => m.CartId == CartId);
            if (val == null)
            {
                return NotFound();
            }

            return View(val);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int CartId)
        {
            var val =  fd.Cart.Find(CartId);
            fd.Cart.Remove(val);
            fd.SaveChanges();
            return RedirectToAction("Viewcart");
        }
        public IActionResult Emptylist()
        {
            string UserId = HttpContext.Session.GetString("UserId");
            int b = int.Parse(UserId);

            List<Cart> list = (from i in fd.Cart
                               where i.UserId == b
                               select i).ToList();
            foreach (var item in list)
            {
                var val = fd.Cart.Find(item.CartId);
                fd.Cart.Remove(val);
                fd.SaveChanges();
            }

            return RedirectToAction("OrderDetails");
        }
        public IActionResult OrderDetails()
        {
           
            return View(fd.OrderDetails.Include(x=>x.Food).ToList());
        }
       public IActionResult Buy()
        { //   var result=(from i in fd.OrderMasters

            //    select i.TotalPrice).SingleOrDefault();
            //HttpContext.Session.SetString("TotalPrice", "result");
            string UserId = HttpContext.Session.GetString("UserId");
           int b = int.Parse(UserId);
            var result=fd.OrderMasters.SingleOrDefault(m => m.UserId == b);
           
            return View(result);
        }
        [HttpPost]
        [ActionName("Payment")]
        public IActionResult Buy(int OrderId,string Type)
        {
            //string UserId = HttpContext.Session.GetString("UserId");
            //int b = int.Parse(UserId);
            var result = fd.OrderMasters.SingleOrDefault(m => m.OrderId == OrderId); 
            result.Type = Type;
            fd.SaveChanges();
            if (result.Type == "Online")
            {

                return RedirectToAction("Online", new { OrderId = OrderId });
            }
            else
            {
                return RedirectToAction("Offline", new { OrderId = OrderId });
            }
        }
        public IActionResult Online(int OrderId)
        {  
            var result = fd.OrderMasters.SingleOrDefault(m => m.OrderId == OrderId);
            return View(result);
        }
        [HttpPost]
        [ActionName("OnlineType")]
        public IActionResult Online(int OrderId,OrderMaster O)
        {
           
            var result = fd.OrderMasters.SingleOrDefault(m => m.OrderId == OrderId);
            result.BankName = O.BankName;
            result.CardNo = O.CardNo;
            result.CCV=O.CCV;
            fd.SaveChanges();
            return RedirectToAction("ThankYou");
        }
        public IActionResult Offline(int OrderId)
        {
            var result = fd.OrderMasters.SingleOrDefault(m => m.OrderId == OrderId);
            return View(result);
        }
        [HttpPost]
        [ActionName("OfflineType")]
        public IActionResult Offline(int OrderId, OrderMaster O)
        {

            var result = fd.OrderMasters.SingleOrDefault(m => m.OrderId == OrderId);
            result = O;
            fd.SaveChanges();
            return RedirectToAction("ThankYou");
        }
        public IActionResult ThankYou()
        {
            return View();
        }
    }
}

Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FifthTemplateforfoodordering.Models;

namespace FifthTemplateforfoodordering.Controllers
{
    public class FoodsController : Controller
    {
        private readonly FoodContext _context;

        public FoodsController(FoodContext context)
        {
            _context = context;
        }

        // GET: Foods
        public async Task<IActionResult> Index()
        {   
            return View(await _context.Foods.ToListAsync());
        }

        // GET: Foods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Foods
                .FirstOrDefaultAsync(m => m.FoodId == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // GET: Foods/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FoodId,CategoryName,FoodName,price,Image,Detail")] Food food)
        {
            if (ModelState.IsValid)
            {
                _context.Add(food);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Foods.FindAsync(id);
            if (food == null)
            {
                return NotFound();
            }
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FoodId,CategoryName,FoodName,price,Image,Detail")] Food food)
        {
            if (id != food.FoodId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(food);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(food.FoodId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Foods
                .FirstOrDefaultAsync(m => m.FoodId == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var food = await _context.Foods.FindAsync(id);
            _context.Foods.Remove(food);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
            return _context.Foods.Any(e => e.FoodId == id);
        }
    }
}

Views/Cart/AddtoCart.cshtml
@model FifthTemplateforfoodordering.Models.Food

@{
    ViewData["Title"] = "AddtoCart";
}

<h1>AddtoCart</h1>

<h4>Food</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddtoCart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FoodId" />
           
            <div class="form-group">
                <label asp-for="FoodName" class="control-label"></label>
                <input asp-for="FoodName" class="form-control" />
                <span asp-validation-for="FoodName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
          


             <div class="form-group">    
                 <label>Quanity</label>
           <input type="number" name="Qnt" value="1" min="1"   id="Qnt"/>
                   
                </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Cart/Buy.cshtml
@model FifthTemplateforfoodordering.Models.OrderMaster

@{
    ViewData["Title"] = "Buy";
  
}

<h1>Buy</h1>

<h4>OrderMaster</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Payment" asp-for="OrderId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            @*<div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div>
               @Html.RadioButtonFor(model => model.Type,"Online", new { onchange = "this.form.submit();" })Online
  @Html.RadioButtonFor(model => model.Type,"Offline", new { onchange = "this.form.submit();" })Offline

            </div>
          
        </form >

    </div>
</div>

Views/Cart/Cart.cshtml
@model FifthTemplateforfoodordering.Models.Cart

@{
    ViewData["Title"] = "Cart";
}

<h1>Cart</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Cart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CartId" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodId" class="control-label"></label>
                <select asp-for="FoodId" class="form-control" asp-items="ViewBag.FoodId"></select>
                <span asp-validation-for="FoodId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qnt" class="control-label"></label>
                <input asp-for="Qnt" class="form-control" />
                <span asp-validation-for="Qnt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Order" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Cart/Delete.cshtml
@model FifthTemplateforfoodordering.Models.Cart

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FoodId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Food.FoodId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qnt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qnt)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CartId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
    </form>
</div>

Views/Cart/MyCart.cshtml
@using Microsoft.AspNetCore.Http
@model FifthTemplateforfoodordering.Models.Cart
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "MyCart";
    ViewBag.FoodId = @HttpContextAccessor.HttpContext.Session.GetString("FoodId");
}

<h1>MyCart</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="MyCart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId" />
                 @*<label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class ="form-control" asp-items="ViewBag.User_ID" />*@
              @*  <input asp-for="Suppid" class="form-control" />*@
            </div>
            <div class="form-group">
                <label asp-for="FoodId" class="control-label"></label>
                <input asp-for="FoodId" class ="form-control" asp-items="ViewBag.FoodId" />
            </div>
            <div class="form-group">
                <label asp-for="Qnt" class="control-label"></label>
                <input asp-for="Qnt" class="form-control" />
                <span asp-validation-for="Qnt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Cart/Offline.cshtml
@model FifthTemplateforfoodordering.Models.OrderMaster

@{
    ViewData["Title"] = "Offline";
}

<h1>Offline</h1>

<h4>Cash On Delivery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="OfflineType" asp-for="OrderId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Pay Now" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Cart/Online.cshtml
@model FifthTemplateforfoodordering.Models.OrderMaster

@{
    ViewData["Title"] = "Online";
}

<h1>Online</h1>

<h4>OrderMaster</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="OnlineType" asp-for="OrderId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           <input type="hidden" asp-for="OrderId" />
            
            
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <select asp-for="BankName" class="form-control" >  
    <option >SBI</option>  
    <option >Kotak Mahindra</option>  
    <option >CUB</option> 
     <option >State Bank</option>
</select>
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardNo" class="control-label"></label>
                <input asp-for="CardNo" class="form-control" />
                <span asp-validation-for="CardNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CCV" class="control-label"></label>
                <input asp-for="CCV" class="form-control" />
                <span asp-validation-for="CCV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Cart/OrderDetails.cshtml
@model IEnumerable<FifthTemplateforfoodordering.Models.OrderDetails>

@{
    ViewData["Title"] = "OrderDetails";
}

<h1>OrderDetails</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderId)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.FoodId)*@Food Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qnt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.Food.FoodName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qnt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPrice)
            </td>
           
          </tr>
        
}
    </tbody>
</table>
<form asp-action="Buy">
    <input type="submit" value="Buy" class="btn btn-success" />
</form>

Views/Cart/ThankYou.cshtml
@{
    ViewData["Title"] = "ThankYou";
}

<div class="jumbotron text-center">
  <h1 class="display-3">Thank You for Shopping!</h1>
  <hr>
  
  <p class="lead">
    <a class="btn btn-primary btn-sm" asp-controller="Foods" asp-action="Index" role="button">Continue Shopping</a>
  </p>
</div>

Views/Cart/ViewCart.cshtml
@model IEnumerable<FifthTemplateforfoodordering.Models.Cart>

@{
    ViewData["Title"] = "ViewCart";
}

<h1>ViewCart</h1>


<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>*@
            
            <th>
                @*@Html.DisplayNameFor(model => model.FoodId)*@Food Name
            </th>
            <th>
                Price
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qnt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           @* <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>*@
             @*<td>
                @Html.DisplayFor(modelItem => item.User.FName)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Food.FoodName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Food.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qnt)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.CartId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<form asp-action="ViewCart">
       <input type="submit" value="Order" asp-action="ViewCart" class="btn btn-success" />
        @*<a asp-action="Index">Back to List</a>*@
    </form>
   
        